/* GTK4/libadwaita — Catppuccin Mocha color overrides */

@define-color window_bg_color @@BASE@@;
@define-color window_fg_color @@TEXT@@;
@define-color view_bg_color @@MANTLE@@;
@define-color view_fg_color @@TEXT@@;
@define-color headerbar_bg_color @@MANTLE@@;
@define-color headerbar_fg_color @@TEXT@@;
@define-color headerbar_border_color @@MANTLE@@;
@define-color card_bg_color @@SURFACE0@@;
@define-color card_fg_color @@TEXT@@;
@define-color dialog_bg_color @@SURFACE0@@;
@define-color dialog_fg_color @@TEXT@@;
@define-color popover_bg_color @@SURFACE0@@;
@define-color popover_fg_color @@TEXT@@;
@define-color sidebar_bg_color @@CRUST@@;
@define-color sidebar_fg_color @@TEXT@@;
@define-color sidebar_backdrop_color @@MANTLE@@;
@define-color sidebar_shade_color rgba(0, 0, 0, 0.36);
@define-color secondary_sidebar_bg_color @@CRUST@@;
@define-color secondary_sidebar_fg_color @@TEXT@@;
@define-color secondary_sidebar_backdrop_color @@MANTLE@@;
@define-color accent_bg_color @@MAUVE@@;
@define-color accent_fg_color @@CRUST@@;
@define-color accent_color @@MAUVE@@;
@define-color destructive_bg_color @@RED@@;
@define-color destructive_fg_color @@CRUST@@;
@define-color destructive_color @@RED@@;
@define-color success_bg_color @@GREEN@@;
@define-color success_fg_color @@CRUST@@;
@define-color success_color @@GREEN@@;
@define-color warning_bg_color @@YELLOW@@;
@define-color warning_fg_color @@CRUST@@;
@define-color warning_color @@YELLOW@@;
@define-color error_bg_color @@RED@@;
@define-color error_fg_color @@CRUST@@;
@define-color error_color @@RED@@;
@define-color borders alpha(@@TEXT@@, 0.15);
@define-color shade_color rgba(0, 0, 0, 0.36);
@define-color scrollbar_outline_color @@SURFACE1@@;
